PumasAI/QuartoNotebookRunner.jl

.github/workflows/CI.yml
test/runtests.jl

The worker processes running the notebooks appear to stall on macOS 1.6 when precompiling some of the more costly notebook project environments. Avoid that by running the precompilation separately prior to starting the tests.
Adds the cache action to try to save as much of that precompilation work as possible.

Fix CI issues on macOS 1.6

---

src/server.jl
src/worker.jl
test/examples/integrations/CairoMakie.qmd
test/runtests.jl

Only attempt to rerun hooks for packages that have actually already been loaded, otherwise version checks will fail since the package isn't actually loaded. Cache package version as an optimisation.

Fix package integration hooks logic

---

src/precompile.jl

1.10 during precompilation has some warnings due to tasks hanging. This is due to the `Malt` workers. Skip these parts of the precompilation so that we don't run into that warning.
Fixes #8.

Adjust precompile workload to avoid warnings

---

bin/pluto.jl

- convert admonitions
- add `let ... end` blocks
- format: indent = 4
- add more frontmatter stuff

feat: improvements over Pluto conversions

---

src/server.jl
src/worker.jl
test/examples/integrations/CairoMakie.qmd
test/examples/integrations/Plots.qmd
test/runtests.jl

Copying a message from Slack:
> the way it works in Makie 0.20 is that we mostly treat the unit in px_per_unit as the CSS px, or device independent pixel. The px in px_per_unit is then the real image pixel. When a quarto document requests some dpi which means dots per inch, or effectively pixels per inch these days, then the pixels in that is referring to real image pixels. And inch is obviously a real-world metric that doesn't change, but so is the CSS pixel, which has a fixed conversion to inches.
So, we want to convert the fig_width and fig_height which are given in inches to CSS pixels. This is done by multiplying with 96. Then these numbers should be the Makie figure size. The px_per_unit value we need to set to achieve the given dpi we can calculate similarly. 300 dots per inch == …

Fix CairoMakie behavior for figure width and dpi settings

---

test/examples/integrations/Plots/Project.toml

There appears to be some breakage on the most recent version of this package that is causing the REPL to hang, or segfault on tests. Just pin its version for now.

Pin `Plots` version

---

.github/workflows/CI.yml
src/server.jl
src/socket.jl
test/runtests.jl

Removing use of `showprogress = true` appears to be the main factor here. Also reduce the number of `mktempdir` calls might be involved.

Improve stability of tests

---

src/server.jl
src/socket.jl
test/runtests.jl

Allow passing extra frontmatter into `run!` and into the socket server.
The `A way to share YAML configuration across multiple documents.` part of #16.

Project frontmatter

---

src/server.jl
test/runtests.jl

Fixes #21, correct syntax highlighting of Julia code blocks.

Add additional `metadata` to `ipynb` output

---

src/server.jl
test/Project.toml
test/runtests.jl
test/testsets/error_configuration/01.jl
test/testsets/error_configuration/01.qmd
test/testsets/error_configuration/02.jl
test/testsets/error_configuration/02.qmd

In frontmatter under the `execute` key and within cells as the `error` key.

Allow setting `error` to control reporting of cell errors

---

src/worker.jl
test/testsets/semicolons.jl

To match the behaviour of the Julia REPL. This is an alternative to the `#| output: false` cell option.

Add support for suppressing output via `;`

---

test/utilities/project_precompile.jl

Some warnings were appearing in CI that may be related to this, replicating some of the Plots.jl CI config here to see whether it helps silence things.

Add GKS* env vars in CI

---

src/server.jl
test/testsets/cell_options.jl

Support full YAML syntax rather than just single line key/value pairs.

Fix #30, correct YAML handling in cells

---

src/server.jl
src/worker.jl
test/testsets/inline_code.jl

The behaviour of `AbstractString` printing and escaping needs to be decided on here. Worth seeing what the other languages actually do.

Fix #15, inline code

---

src/socket.jl
test/testsets/socket_server/client.js
test/testsets/socket_server/socket_server.jl

`isopen` can be used to check that a file already has a worker opened for it, which can then be `close`d if desired. The `isready` command is just to have something for quarto to establish that the server is functioning at all, before sending further commands to it.
Fixes https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/39

Add `isopen` and `isready` commands to server protocol

---

src/precompile.jl
src/socket.jl

To improve responsiveness of first render using quarto, include a basic server socket connection pass in the precompilation run. Ideally, this would include `run` but it seems that wasn't desired due to #8

Precompile server machinery

---

src/socket.jl

Just had to debug a situation where a file couldn't be executed using quarto, had to resort to running `QuartoNotebookRunner` manually because the only response I got was `running file failed`.
Sending the full julia error back should make this easier in the future.

Return julia error so that quarto can display why execution failed

---

src/server.jl
src/socket.jl

Got a key error on `env` when running a qmd with only exeflags set from quarto.

`get` exeflags and env keys with fallback

---

src/precompile.jl
src/socket.jl

Currently, the code calling `serve` from quarto is unnecessarily complex. It has to choose an open port by opening a server itself on random ports until it finds an open one, then close it and open the QuartoNotebookRunner server on that port. It's easier to just let `serve` call `listenany` itself when no port is specified. The port can then be returned via a wrapper server object.
I also moved the `listen` part out of the `@spawn` because before, I'd have to do a test connection to see if inside the task, the listening might have worked or not. By moving it in front, the `serve` function will block until the listening server is established, so the quarto code should be free to connect to it once it returns.
I also need a way to return the HMAC signing key later to implement the security …

Encapsulate server connection logic

---

src/server.jl
test/testsets/concurrency.jl

- add locks to server and files
- create `borrow_file!` mechanism for simplifying concurrency
- format
- add concurrency test
After adding locks almost to everything, I've simplified the approach so that now, you "borrow" a file (which may optionally create it if you specify that) and while it's borrowed, it is inaccessible to any other task. All the functions mutating `File`s are then expected to be run under this borrowing approach, as making them all threadsafe would be much more difficult.
After this PR, I can use the mechanism to add asynchronous timeouts on top.

Improve thread-safety

---

src/server.jl
test/examples/timeout.qmd
test/testsets/concurrency.jl
test/testsets/worker_timeouts.jl

Workers will by default time out after 300 seconds, like in quarto. `false` will set an immediate timeout (like calling `close!` directly after `run!` and otherwise numbers give the timeout duration in seconds.
Also changes the behavior of `close!` to return whether closing the file succeeded or not, because I was starting to add too many try-catches and with async behavior it's expected that files to be closed are already closed.

Add timeout feature for workers

---

src/server.jl
src/socket.jl
test/testsets/socket_server/socket_timeout.jl

I noticed that the timeout logic didn't quite make sense the way I previously wrote it. Before, the timer started when the last command was processed. But this meant that the server would shut down even if workers were still idling. I overlooked that users will probably not think about the control server at all (that all happens in the background) but they do want to set daemon timeouts in their quarto notebooks. If they think it's practical to keep some notebook alive for three hours, the control server should not say "nothing going on, shutting down" after five minutes.
So here I change the logic such that the timer is only started when the worker count goes to zero. As all workers time out at somepoint when used from quarto, this should give the desired behavior of workers timing out …

Timeout server only if no workers are present

---

src/worker.jl
test/examples/cell_expansion.qmd
test/testsets/cell_expansion.jl

The multicell pipeline did not work with structs defined in the notebook, both because of `get` not being overloaded and because of world age problems.

Support new structs for multicells

---

src/server.jl
src/socket.jl
test/testsets/socket_server/client.js
test/testsets/socket_server/socket_timeout.jl

There was no way for quarto to inform the user where in the rendering process the worker was, because the progress meter is only shown in the server's console.
This PR adds the option to pass a callback function into `run!` that is called before a code chunk should be evaluated. The index of that chunk in the list of all chunks that can be evaluated is then sent over the tcp connection along with the line and source of that chunk.
I've passed on my first idea to capture and send over stdout/stderr while QuartoNotebookRunner is going, because that would send errors twice and could easily get messy because the output will not be formatted for the client. And it's more complex to implement, too. This version here is nice and predictable.
On the quarto side, I have implemented the …

Progress updates for `"run"` command over socket server

---

src/server.jl
src/worker.jl
test/examples/cell_expansion.qmd

It does communicate a bit better what's going on, and `multiple` implies there need to be >1 outputs, which is not true.

Rename `multiple` cell option to `expand`

---

src/socket.jl
test/testsets/socket_server/hmac_signing.jl

While we cannot be certain that this fixes the hang described in https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/91 it at least makes more sense to disallow a client that doesn't send compatible data to continue doing so.
If hangs keep appearing for other users, we can try to look into other solutions.

Close socket when receiving invalid json or hmac

---

src/server.jl
test/examples/integrations/R_code_blocks_with_RCall.qmd
test/testsets/integrations/R_code_blocks_with_RCall.jl

Code blocks with `{r}` undergo a simple source transformation which adds code that checks that the `RCall` symbol is available and points to the expected module. If that's the case, the whole cell (minus cell options) is treated as a string to be used inside the `RCall.R_str` macro, the return value of which is `RCall.rcopy`d to the Julia side again, to be used as the cell output.
For the code output we have to be a bit tricky to get R syntax highlighting. The actual code cell is always going to be treated as julia because the ipynb format doesn't support multiple languages. But we can insert a simple markdown cell with an R code block into which we copy the source code minus cell options. The code with cell options remains in the code cell but that one gets the `echo: false` option added …

Add ability to render R code blocks with RCall

---

src/server.jl
test/examples/parameters.qmd
test/testsets/parameters.jl

Fixes #36 
Dicts are merged recursively, so one could use dicts as parameters and override only some of their values via CLI. I think that matches how we do merging in other places.
Example `parameters.qmd`:
````md
---
engine: julia
title: Parameters
params:
a: 1
b: [1, 2, 3]
---
a is `{julia} a` and b is `{julia} b`
```{julia}
a .+ b
```
````
Then `quarto render parameters.qmd --to=html -P a:2`:

Implement parameters

---

Project.toml

More correctly reflects the code owners of this package.

Update `authors` field

---

src/worker.jl
test/examples/cell_expansion.qmd
test/examples/cell_expansion_errors.qmd
test/testsets/cell_expansion.jl

Before, when any of the conditions for using the output of an expanded cell didn't hold, you'd crash the worker with some obscure error like `cannot iterate MethodError` or so. Now, these cases are all caught separately and given explanatory error messages.

Error handling for expanded cells

---

src/server.jl
test/examples/project.qmd
test/examples/project/dir/project_default.qmd
test/examples/project/project_default.qmd
test/examples/project_env.qmd
test/examples/project_exeflags.qmd
test/testsets/env_and_exeflags.jl

for https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/69

make '--color=yes' the default

---

src/QuartoNotebookRunner.jl
src/utilities.jl

From https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/136 it's clearly difficult to correctly setup `quarto` to correctly run the backend using a particular PR's branch so that we can more easily have people verify that a fix is correct. This helper aims to make that much simpler.
@jkrumbiegel I'm not 100% sure that `--no-execute-daemon` is having the intended effect on reruns, see the below outputs. In particular the differences between the `Transport file` logs, the first of which I'd expect, but the second one is saying it is reusing the server, even though `--no-execute-daemon` flag is passed. Any idea what's happening there?
```
julia> QuartoNotebookRunner.test_pr(`quarto render test/examples/integrations/Plots.qmd`; rev = "mh/plots-pdf")
Updating git-repo …
```

Add `test_pr` for testing PRs

---

src/QuartoNotebookWorker/src/render.jl

For trying out things quickly it can be nice to do `using QuartoNotebookWorker` and then overloading its `expand` function for some struct defined there.

invokelatest expand to allow extension within notebook

---

README.md

Since packages that would want to extend QNW would need `QuartoNotebookWorker` in their weakdeps and that requires that the weakdep be registered for registry CI checks to pass. Extending with `Requires.jl` does not have that issue since it is dynamic rather than based on what the manifest resolves to.

Document using `Requires.jl` for extending in 3rd-party packages

---

src/QuartoNotebookWorker/src/render.jl
src/server.jl
src/worker.jl
test/testsets/inline_code.jl

Fixes https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/152

`print` inline code results instead of `show`ing them

---

src/QuartoNotebookWorker/ext/QuartoNotebookWorkerPlotlyBaseExt.jl
src/QuartoNotebookWorker/ext/QuartoNotebookWorkerPlotlyJSExt.jl
src/QuartoNotebookWorker/src/render.jl
test/testsets/integrations/PlotlyJS.jl

Quarto expects the preamble for a Plotly plot using require.js to exist in a cell only once. So we keep track whether a PlotlyBase plot has already been displayed, and only if not, we expand the plot into two cells, the preamble and the plot's html.
The fix on the quarto side is not in a prerelease, yet, but locally I confirmed that this works with latest master:
````
---
engine: julia
keep-md: true
---
```{julia}
using PlotlyJS
plot(rand(10,4))
```
and another plot
```{julia}
plot(cumsum(randn(100)))
```
````

Fix Plotly require.js config mechanism

---

src/QuartoNotebookWorker/ext/QuartoNotebookWorkerCairoMakieExt.jl
src/QuartoNotebookWorker/src/NotebookState.jl
src/QuartoNotebookWorker/src/refresh.jl
src/QuartoNotebookWorker/src/render.jl
src/QuartoNotebookWorker/test/runtests.jl
src/WorkerSetup.jl
src/worker.jl
test/worker_tests.jl

Handles the case where a package that triggers extension loading within this package's worker package is already available in the process that is running the notebook (e.g. a system image containing `Makie`).

Fix unpopulated notebook options during worker package init

---

src/server.jl
test/examples/evalfalse.qmd
test/testsets/evalfalse.jl

Fixes #173 
If `eval: false` is set globally, either via frontmatter or through quarto, only cells which explicitly have `eval: true` set will be evaluated.

Fix global `eval: false`

---

README.md

I am suggesting an extension to the README file to address #195.

Information about current Quarto upstream issues

---

.github/workflows/CI.yml
src/QuartoNotebookWorker/src/NotebookState.jl
src/QuartoNotebookWorker/src/render.jl
src/worker.jl

Fixes #190.
There's a number of other test failures due to assumptions hardcoded in specific tests that will also need to be addressed before CI will pass.

Fix Julia 1.11 errors

---

.ci/Project.toml
src/QuartoNotebookWorker/src/render.jl
src/precompile.jl
src/server.jl

Reverts PumasAI/QuartoNotebookRunner.jl#199. v2 was yanked from the registry.

Revert "Pin `JuliaFormatter` to `v2` and fix new formatting failures"

---

src/server.jl
test/examples/exeflags_merging.qmd
test/testsets/exeflags_merging.jl

Changes the behavior of the `QUARTONOTEBOOKRUNNER_EXEFLAGS` env variable in conjunction with the `exeflags` frontmatter variable.
Before, the env variable would only have an effect if no frontmatter variable was specified. Frontmatter exeflags would fully override env exeflags. This is impractical if the env specifies a sysimage to use system-wide but a user wants to change only the number of threads for some notebook.
Therefore, this PR appends the user-specified exeflags to the env-specified ones. This has the effect of merging them as Julia ignores earlier instances of the same flags.

Append user exeflags to env exeflags

---

CHANGELOG.md
src/QuartoNotebookWorker/src/render.jl
test/examples/stdout.qmd
test/testsets/stdout.jl

Fixes #249 by passing the process color setting to the `IOContext` that handles printing cell results.
The issue example now shows as below for me: <img width="841" alt="image" src="https://github.com/user-attachments/assets/ab1f6856-b9de-4169-b5fd-940ac0d1729a" />
@ajinkya-k if you're able to confirm this fixes it for you locally that would be great, thanks.

Fix #249, color printing of cell results

---

CHANGELOG.md
src/QuartoNotebookWorker/src/InlineDisplay.jl
src/QuartoNotebookWorker/src/render.jl
test/examples/display-mime.qmd
test/testsets/display-mime.jl

Should resolve the issue found in #251. Thanks for reporting that @pierrethiriet.
Before this change our custom `InlineDisplay` that catches all `display` calls in cells and displays them to the correct IO did not have a dispatch for `display(::MIME, value)`, only `display(value)` was intercepted.
---
**Details:**
`PrettyTables` uses https://github.com/ronisbr/PrettyTables.jl/blob/99595fcad38a5181e5888e32267cd045fa5b8669/src/backends/html/html_backend.jl#L517 to print to the right place for HTML output. There is no equivalent in the LaTeX backend for that package though, so setting the backend to LaTeX ends up just printing the output to `stdout`. Luckily it appears that Quarto is able to translate HTML tables that `PrettyTables` generates into suitable LaTeX reasonably well, so just …

Fix #251, add `display` method for `InlineDisplay` with `MIME` (fixes `PrettyTables` rendering)

---

.github/workflows/CI.yml
CHANGELOG.md
src/startup.jl

Adjusts the behaviour of the `startup.jl` script that initialises worker processes and loads the `QuartoNotebookWorker` package into the process. Previously this was done by simply adding the worker package's path to `LOAD_PATH`, with no `Pkg` resolving to create a usable `Manifest.toml`. This was fine since it wasn't at the start of the load path, but #256 revealed that `PythonCall` introspects all entries in the load path to find it's dependencies. Unresolved environments in the load path threw an error when `Pkg.dependencies()` was called.
Instead we now call `Pkg.develop` to create a new environment that includes `QuartoNotebookWorker` as a dependency. This has the same effect as the original startup script, but ensures that all entries we add to the load path are fully resolved.

Fix #256, adjust `startup.jl` to avoid unresolved environments

---

test/examples/integrations/CairoMakie/Project.toml
test/examples/mimetypes/Project.toml

Until the test failures related to upstream changes are resolved @jkrumbiegel I'm just going to pin the version so that queued PRs are mergable.

Pin `Makie` version, fixes CI failures

---

src/server.jl
test/Project.toml
test/examples/integrations/CairoMakie.qmd
test/examples/integrations/CairoMakie/Project.toml
test/examples/mimetypes/Project.toml
test/testsets/integrations/CairoMakie.jl
test/testsets/package_integration_hooks.jl
test/testsets/png_metadata.jl
test/testsets/project_frontmatter.jl
test/utilities/prelude.jl

Instead of just changing all the tested metadata values to the same values given figure size (because they don't reflect dpi) I've added tests for both logical and real image size everywhere.

Unpin Makie and fix tests

---

CHANGELOG.md
src/server.jl

`Sys.which` can fail to find a binary if there are permission issues with the file, even if it can run via `run`. This adjusts the way we check for the `juliaup` binary to use `success` instead.

Check for `juliaup` more robustly

---

README.md

The current README.md contains a lot of developer documentation, but no user documentation. I guess we should just link to https://quarto.org/docs/computations/julia.html at the top? Perhaps this link should also be put as URL in the GitHub repo About section?

Add link to Quarto Julia docs

---

CHANGELOG.md
src/server.jl

This linked PR is changing the way that several `QUARTO_*` environment variables are forwarded to the engine. Instead of just being available via `ENV` they are passed in a `.env` field in the options JSON that Quarto passes to QNR. Pick out the env vars if they exist and add them to the notebook process's env vars.
Cc @cscheid, this will provide the fix needed for https://github.com/quarto-dev/quarto-cli/pull/12621.

Forward envvars from JSON payload
